export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1 style={{padding:"1rem",backgroundColor:"lightgreen"}} >Header</h1>
        </header>
        {children}
        <footer>
          <h1 style={{padding:"1rem",backgroundColor:"lightyellow"}} >
              Footer
          </h1>
          </footer>
      </body>
    </html>
  )
}
